### ISSUE TITLE
Custom dataset training

### ISSUE THREAD

**Issue by MiladGhorbaniG** [SJTU-LuHe/TransVOD#15]
I would like to train a model with my custom dataset, so I wonder how the dataset should be; its format, and JSON files?

**Comment by MiladGhorbaniG** [comment]
I just checked the json files and found out how the datasets should be. So I close this issue

**Comment by Sairam13001** [comment]
Hai @MiladGhorbaniG, I am trying to train on a custom video dataset. Could you kindly let me know how I should prepare my dataset? 

In this work, they are using ILSVRC2015 DET and VID videos for training. I can use my custom dataset in place of ILSVRC2015 VID, then, what can I do about ILSVRC2015 DET?  Can I use "ILSVRC2015 DET" and "Custom Dataset" for training on my dataset?

**Comment by YangBo0411** [comment]
> I just checked the json files and found out how the datasets should be. So I close this issue

How did you solve this problem? I'm having the same issue now

**Comment by weiyingxue** [comment]
How did you solve this problem? I'm having the same issue now
