### ISSUE TITLE
Very low precision on custom dataset

### ISSUE THREAD

**Issue by zzzbzzz** [SJTU-LuHe/TransVOD#28]
Very nice work and thank you for sharing the code. However, when I used the multi-frame model on my own dataset, I got very low precision near zero, while the single-frame deformable DETR obtained 20 to 30 mAP, which is normal for my dataset. I followed the default settings in my implementation. I wonder what might be the reason and can you upload the training logs for reference?

**Comment by fisal-ITS** [comment]
Hi, Have you solved the problem? I also get very small precision close to zero when using my own dataset. Could you please provide information on how you solved it?

**Comment by nbharathik** [comment]
Hey there, 

I would also like to know, how you have solved the problem.

**Comment by YangBo0411** [comment]
> Very nice work and thank you for sharing the code. However, when I used the multi-frame model on my own dataset, I got very low precision near zero, while the single-frame deformable DETR obtained 20 to 30 mAP, which is normal for my dataset. I followed the default settings in my implementation. I wonder what might be the reason and can you upload the training logs for reference?

Would like to ask you how you solved this problem, I had the same problem

**Comment by nbharathik** [comment]
Solved here in #36
