### ISSUE TITLE
Custom dataset training 

### ISSUE THREAD

**Issue by Sairam13001** [SJTU-LuHe/TransVOD#31]
Thank you for the great work and making code public. 

Suppose I want to train on my own video dataset, say X. (I can replace "ILSVRC2015 VID" with X).  Then what dataset should I use in place of ILSVRC2015 DET?

Kindly let me know. Thank you.

**Comment by YangBo0411** [comment]
> Thank you for the great work and making code public.
> 
> Suppose I want to train on my own video dataset, say X. (I can replace "ILSVRC2015 VID" with X). Then what dataset should I use in place of ILSVRC2015 DET?
> 
> Kindly let me know. Thank you.

Have you solved this problem? I'm having the same issue.
