### ISSUE TITLE
When will the code be made available? The accept notification of ACM MM has already been released.

### ISSUE THREAD

**Issue by haifangong** [SJTU-LuHe/TransVOD#4]

**Comment by SJTU-LuHe** [comment]
Sorry for the late reply. We have released our source code and pre-trained models on: https://github.com/SJTU-LuHe/TransVOD  .
We hope our paper and code will be helpful for your further research. Thanks for your interest in our work.
If you have any questions, feel free to pull a request to an issue in our Github repository.
