### ISSUE TITLE
Will the code be available soon?

### ISSUE THREAD

**Issue by hcmea** [SJTU-LuHe/TransVOD#8]
Thanks for this great study. I am so interested in Trans-VODs. Hope to see the code available in here.

**Comment by abdussamettrkr** [comment]
I think the results are not reproducible. So, they do not publish their code.

**Comment by SJTU-LuHe** [comment]
The code will be released in this weekend.  Thanks for your attention to our research.

**Comment by LiYan0306** [comment]
I'm so excited to waiting for your released！！
