### ISSUE TITLE
Can you provide demo script?

### ISSUE THREAD

**Issue by xiaocc612** [SJTU-LuHe/TransVOD#9]
Thanks.

**Comment by SJTU-LuHe** [comment]
We do not provide demo script. if needed,  please refer to https://github.com/open-mmlab/mmtracking

**Comment by xiaocc612** [comment]
> We do not provide demo script. if needed, please refer to https://github.com/open-mmlab/mmtracking

Thanks.

**Comment by zoelevin** [comment]
Were you able to create your own demo script for this xiaocc612? I'm a bit confused on how to run our own videos and see the object detection working.
